build-android:
	go build -buildmode=c-shared -o syncthing.a syncthing.go

build-ios:
	go build -buildmode=c-shared -o syncthing.a syncthing.go

build-win:
	go build -buildmode=c-shared -o syncthing.a syncthing.go